export const CREATE_LINE = 'CREATE_LINE';
export const DELETE_LINE = 'DELETE_LINE';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const UPDATE_DECLARATION = 'UPDATE_DECLARATION';
export const UPDATE_EXPRESSION = 'UPDATE_EXPRESSION';
export const UPDATE_FUNCTION = 'UPDATE_FUNCTION';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';
