export const CREATE_LINE = 'CREATE_LINE';
export const DELETE_DECLARATION = 'DELETE_DECLARATION';
export const DELETE_LINE = 'DELETE_LINE';
export const TURN_EXPRESSION_INTO_FUNCTION_CALL =
  'TURN_EXPRESSION_INTO_FUNCTION_CALL';
export const UPGRADE_EXPRESSION_TO_BINARY = 'UPGRADE_EXPRESSION_TO_BINARY';
export const UPGRADE_EXPRESSION_WITH_UNARY_OPERATOR =
  'UPGRADE_EXPRESSION_WITH_UNARY_OPERATOR';
export const UPGRADE_LINE_TO_ASSIGNMENT = 'UPGRADE_LINE_TO_ASSIGNMENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const UPDATE_VALUE_AT_PATH = 'UPDATE_VALUE_AT_PATH';
export const UPDATE_FUNCTION = 'UPDATE_FUNCTION';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';
